### ISSUE TITLE
Self-intersecting surfaces (darmstadt-maske v1, Simplify3D)

### ISSUE THREAD

**Issue by MarzelT** [jvanbalen/darmstadt-maske#1]
Beim Slicen erstellt Simplify3D Hohlräume an den Kontaktpunkten mit den Haken und Pins. Eine Meshanalyse zeigt "self-intersecting surfaces" (siehe Bild, rot markiert). 

Als workaround kann in Simplify3D "Mesh >> Separate connected surfaces" ausgeführt werden. Das STL wird dann in Einzelteile zerlegt, welche über den gemeinsamen Druckprozess aber lückenlos zusammengefügt werden. 

![self-intersecting_surfaces](https://user-images.githubusercontent.com/36676073/78336214-4d8bc480-758f-11ea-9bbd-02fcbbeb5c69.png)

**Comment by jvanbalen** [comment]
Bei mir im Prusa-Slicer passiert das interessanterweise nicht. Ich habe mal das Reparatur-Tool von Prusa verwendet und das in den branch fix/intersecting-surfaces geschoben. Geht das jetzt bei dir?

**Comment by Phil1988** [comment]
ist nicht mehr nötig.

Cura und der Prusa Slicer haben damit keine Probleme. Bei S3D stimmt es.

**Comment by jvanbalen** [comment]
Sollte mit #3 geschlossen sein. Den experimentellen branch habe ich wieder gelöscht.
